[package]
name = "fsevents-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fsevent-sys = "4.1.0"
napi = {version=  "2.16.17", features = ["napi4"]}
napi-derive = "2.16.13"
paste = "1.0.15"

[build-dependencies]
napi-build = "2.1.6"

[lib]
crate-type = ["cdylib"]
